### ISSUE TITLE
Update to new format

### ISSUE THREAD

**Issue by lauraclay** [raspberrypilearning/python-intro#3]
- [ ] cover.png
- [x] LICENCE.md
- [x] CONTRIBUTING.md
- [x] meta.yml
- [x] hardware.yml
- [x] software.yml
- [x] extras.yml
- [x] overview.md
- [x] learn.md

**Comment by lauraclay** [comment]
Only added the three files for now until it's converted into a worksheet proper.

**Comment by bennuttall** [comment]
I've converted this to the worksheet format in [Getting Started with Python](https://github.com/raspberrypilearning/getting-started-with-python) - just needs finishing off and I think it should replace this resource.
